# Site settings
title: Tangrui Song's Fantasy World
email: "trsong.cs@gmail.com"
description: Talk is cheap; Shall we start coding?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trsong.github.io" # the base hostname & protocol for your site
twitter_username: tangrsong
github_username:  trsong
encoding: "utf-8"
permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true


theme: jekyll-theme-leap-day